### ISSUE TITLE
Is this still needed for rtl88x2bu support into OpenWRT ?

### ISSUE THREAD

**Issue by cristian-ciobanu** [mirobiala/rtl88x2bu-cl#1]
I just saw this commit on OpenWRT main branch https://github.com/openwrt/openwrt/commit/12ef0be4fe76324de1ca3ee103c7027dae9c7985.

I wonder if this commit bring rtl88xbu support into OpenWRT or do I still need to add the repository to compile rtl88x2bu module into OpenWRT ?

**Comment by mirobiala** [comment]
This commit is new to me, too :) . I will try it and compare it to the [@RinCat](https://github.com/RinCat)'s driver for performance and usability and let you know, if you are still interested :) .

If it is working as it's should be, my patch won't be needed.

Regards!

**Comment by cristian-ciobanu** [comment]
Yes please let me know your tests outcome. 
Thank you.

**Comment by mirobiala** [comment]
_Test results_: 

**Good news**:
- Successfully compiled the latest **master** branch of OpenWRT. I can confirm that branch includes support for rtl8822bu (kmod-rtw88-8822bu exists as option).
- On boot brings up the device and you can set it up via Luci.

**Bad news**:
- Most of the issues I've been struggle when I was starting to compile the [@RinCat](https://github.com/RinCat)'s driver for OpenWRT exists in that kernel module:
- When set a single AP, I can connect to it but when try to use it : 
`rtw_8822bu 1-4:1.0: timed out to flush queue 3` and **disconnects**!
- When set Mesh point (802.11s) in addition to the AP, the mesh point remains not active even enabled (with module crash).
- When set second AP, the both APs are become not active (with module crash).
- The crash itself:
`[  138.325740] RIP: 0010:0xffffffffa05ac3da
[  138.326255] Code: 68 c7 5d a0 e8 d1 19 4a e1 0f 0b 48 83 c4 18 5b 41 5c 41 5d 41 5e 41 5f 5d e9 32 45 85 e1 48 c7 c7 fe c6 5d a0 e8 b0 19 4a e1 <0f> 0b e9 62 fd ff ff 66 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 40 00
[  138.328311] RSP: 0018:ffffc900011ef908 EFLAGS: 00010296
[  138.328930] RAX: 0000000000000018 RBX: ffff88800436a080 RCX: 0000000000000027
[  138.329764] RDX: ffff88803ec1c588 RSI: 0000000000000001 RDI: ffff88803ec1c580
[  138.330567] RBP: ffffc900011ef948 R08: 0000000000000000 R09: ffffc900011ef718
[  138.331370] R10: ffffc900011ef710 R11: ffffffff824ae3c8 R12: 0000000000000000
[  138.332173] R13: 0000000000000002 R14: 0000000000000003 R15: 0000000000000000
[  138.332973] FS:  00007f53d9c30b48(0000) GS:ffff88803ec00000(0000) knlGS:0000000000000000
[  138.333956] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  138.334700] CR2: 0000564dc0c115ac CR3: 0000000004ff6000 CR4: 0000000000350ef0
[  138.335653] Call Trace:
[  138.336011]  <TASK>
[  138.336327]  ? show_regs.part.0+0x1e/0x24
[  138.336832]  ? show_regs.cold+0x8/0xd
[  138.337306]  ? __warn+0x74/0xf0
[  138.337723]  ? 0xffffffffa05ac3da
[  138.338168]  ? report_bug+0x86/0xa0
[  138.339204]  ? handle_bug+0x38/0x90
[  138.339656]  ? exc_invalid_op+0x18/0x70
[  138.340143]  ? asm_exc_invalid_op+0x1b/0x20
[  138.340664]  ? 0xffffffffa05ac3da
[  138.341098]  ? 0xffffffffa05ac3da
[  138.341546]  0xffffffffa05ac920
[  138.341965]  rtw_core_enable_beacon+0x1b7/0x1720 [rtw88_core]
[  138.342632]  ieee80211_color_change_finish+0x481/0xd30 [mac80211]
[  138.343350]  nl80211_parse_chandef+0x1843/0x3790 [cfg80211]
[  138.344024]  ? rtnl_unlock+0x9/0x10
[  138.344508]  genl_family_rcv_msg_doit+0xc9/0x110
[  138.345070]  genl_rcv_msg+0xcc/0x1b0
[  138.345549]  ? nl80211_parse_chandef+0x1590/0x3790 [cfg80211]
[  138.355980]  ? genl_get_cmd+0xe0/0xe0
[  138.356456]  netlink_rcv_skb+0x52/0x100
[  138.356938]  genl_rcv+0x23/0x40
[  138.357361]  netlink_unicast+0x1ff/0x2e0
[  138.357857]  netlink_sendmsg+0x21d/0x460
[  138.358347]  ? netlink_unicast+0x2e0/0x2e0
[  138.358853]  ____sys_sendmsg+0x232/0x260
[  138.359347]  ? __import_iovec+0x4b/0x160
[  138.359842]  ___sys_sendmsg+0xb3/0xf0
[  138.360307]  ? __mod_memcg_lruvec_state+0x40/0x80
[  138.360872]  ? __mod_lruvec_page_state+0x8e/0xe0
[  138.361460]  ? lru_cache_add_inactive_or_unevictable+0x21/0x80
[  138.362144]  ? __handle_mm_fault+0x936/0xdf0
[  138.362671]  __sys_sendmsg+0x40/0x90
[  138.363139]  ? irqentry_exit+0x1d/0x30
[  138.363618]  __x64_sys_sendmsg+0x18/0x20
[  138.364113]  do_syscall_64+0x42/0x90
[  138.364570]  entry_SYSCALL_64_after_hwframe+0x62/0xcc
[  138.365181] RIP: 0033:0x7f53d9c0f399
[  138.365644] Code: c3 8b 07 85 c0 75 24 49 89 fb 48 89 f0 48 89 d7 48 89 ce 4c 89 c2 4d 89 ca 4c 8b 44 24 08 4c 8b 4c 24 10 4c 89 5c 24 08 0f 05 <c3> e9 c8 cf ff ff 41 54 b8 02 00 00 00 55 48 89 f5 be 00 88 08 00
[  138.367714] RSP: 002b:00007ffe271e4438 EFLAGS: 00000246 ORIG_RAX: 000000000000002e
[  138.369355] RAX: ffffffffffffffda RBX: 000000000000002e RCX: 00007f53d9c0f399
[  138.370163] RDX: 0000000000000000 RSI: 00007ffe271e4488 RDI: 0000000000000003
[  138.370969] RBP: 00007f53d9c30b48 R08: 0000000000000000 R09: 0000000000000000
[  138.371774] R10: 0000000000000000 R11: 0000000000000246 R12: 0000000000000000
[  138.372582] R13: 00007f53d9bb7df0 R14: 00007f53d9c31ec0 R15: 00007f53d9badb30
[  138.373413]  </TASK>`

**Conclusion** :
- That official OpenWRT kernel module for the rtl8822bu is not usable for now (at least for me).
- With that disconnecting issue it can't be used even as single AP.
- I'm sticking with the latest OpenWRT tag 23.05.0 with my patch to bring rtl88x2bu support.
- I tested my patch on 3 different platforms with AP and Mesh Point working together and connected to each other.

Regards!

**Comment by cristian-ciobanu** [comment]
Ok thank you for testing this. 
I guess I will go and use the driver in your repository and compile into OpenWRT based on your testing.

**Comment by mirobiala** [comment]
For OpenWRT **master** branch, now you can use the [snapshot](https://github.com/mirobiala/rtl88x2bu-cl/tree/snapshot) branch of this patch.

Regards!

**Comment by cristian-ciobanu** [comment]
Thank you for your work.
