### ISSUE TITLE
Upstreaming extended associated stations connection info

### ISSUE THREAD

**Issue by alex3d** [mirobiala/rtl88x2bu-cl#10]
Hi! Do you have plans to upstream extended associated stations connection info into Rincat's driver repo?
If you have no such plans then I'm willing to do it.
I mean this part of code:
https://github.com/mirobiala/rtl88x2bu-cl/blob/ca9a7dd983a25deb0888b5ddfd943a7de4f79e9e/patches/0003-custom-configuration.patch#L141-L185

**Comment by mirobiala** [comment]
Hi @alex3d, you can do it if you want. Unfortunately I have no time at the moment to deal with the driver, so thank you for your time and effort!
