### ISSUE TITLE
Not working on snapshot build (no AP)

### ISSUE THREAD

**Issue by pyra92** [mirobiala/rtl88x2bu-cl#4]
First of all thank-you so much for your work on this - always so amazed when open source deliver this sort of solution!

I've been running it on my Raspberry Pi 4b (23.05) firmware and it's awesome - but on Snapshot builds on either Pi 4 or Pi 5 (OpenWrt SNAPSHOT r25279-62acd9a2f9 / 6.1.78) it doesn't work as AP (just shows as disabled). 

<img width="451" alt="Screenshot 2024-02-22 at 13 56 05" src="https://github.com/mirobiala/rtl88x2bu-cl/assets/70330111/a83f43b0-96f2-4551-80ad-2357b32ef36a">

I'd stick to release and not bother about snapshot but it's just that the Pi 5 only is available on Snapshot, but it seems to be same issue on Pi 4 snapshot too so don't think it's a Pi 5 specific issue.

I followed the guide from here (so the one for snapshot) - https://github.com/mirobiala/rtl88x2bu-cl/tree/snapshot

Also noticed in usbutils (lsusb -t) that it shows Class=[unknown] which doesn't happen on the working/master version    |__ Port 001: Dev 002, If 0, Class=[unknown], Driver=rtl88x2bu, 5000M

Just wondering if there's anything I need to change to run it in snapshot / for newer kernels and again thanks for your work on this. Really appreciated.

If helpful this from system log: 
`Thu Feb 22 13:54:01 2024 kern.info kernel: [ 1137.565193] usb 1-1.1: new high-speed USB device number 4 using xhci_hcd
Thu Feb 22 13:54:01 2024 kern.info kernel: [ 1137.695847] usb 1-1.1: New USB device found, idVendor=0bda, idProduct=b812, bcdDevice= 2.10
Thu Feb 22 13:54:01 2024 kern.info kernel: [ 1137.704220] usb 1-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Thu Feb 22 13:54:01 2024 kern.info kernel: [ 1137.711564] usb 1-1.1: Product: USB3.0 802.11ac 1200M Adapter
Thu Feb 22 13:54:01 2024 kern.info kernel: [ 1137.717339] usb 1-1.1: Manufacturer: Realtek
Thu Feb 22 13:54:01 2024 kern.info kernel: [ 1137.721615] usb 1-1.1: SerialNumber: 123456
Thu Feb 22 13:54:02 2024 kern.info kernel: [ 1138.625373] usb 2-1: new SuperSpeed USB device number 3 using xhci_hcd
Thu Feb 22 13:54:02 2024 kern.info kernel: [ 1138.656063] usb 2-1: New USB device found, idVendor=0bda, idProduct=b812, bcdDevice= 3.00
Thu Feb 22 13:54:02 2024 kern.info kernel: [ 1138.664257] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Thu Feb 22 13:54:02 2024 kern.info kernel: [ 1138.671438] usb 2-1: Product: USB3.0 802.11ac 1200M Adapter
Thu Feb 22 13:54:02 2024 kern.info kernel: [ 1138.677043] usb 2-1: Manufacturer: Realtek
Thu Feb 22 13:54:02 2024 kern.info kernel: [ 1138.681163] usb 2-1: SerialNumber: 123456
Thu Feb 22 13:54:04 2024 kern.warn kernel: [ 1140.635393] rtl88x2bu 1-1.1:1.0: Runtime PM usage count underflow!
Thu Feb 22 13:54:04 2024 kern.info kernel: [ 1140.643404] usb 1-1.1: USB disconnect, device number 4
Thu Feb 22 13:54:15 2024 daemon.notice netifd: radio1 (3462): WARNING: Variable 'data' does not exist or is not an array/object
Thu Feb 22 13:54:15 2024 daemon.notice netifd: radio1 (3462): command failed: Invalid argument (-22)
Thu Feb 22 13:54:15 2024 daemon.notice hostapd: Set new config for phy phy2:
Thu Feb 22 13:54:15 2024 daemon.notice wpa_supplicant[935]: Set new config for phy phy2
Thu Feb 22 13:54:15 2024 daemon.notice wpa_supplicant[935]: Set new config for phy phy2
Thu Feb 22 13:54:15 2024 daemon.notice hostapd: Set new config for phy phy2: /var/run/hostapd-phy2.conf
Thu Feb 22 13:54:15 2024 daemon.notice hostapd: Restart interface for phy phy2
Thu Feb 22 13:54:15 2024 daemon.notice hostapd: Failed to create phy2-ap0 on phy phy2: No such device
Thu Feb 22 13:54:15 2024 daemon.notice netifd: Wireless device 'radio1' is now up
Thu Feb 22 13:54:17 2024 daemon.info dnsmasq[1]: read /etc/hosts - 12 names
Thu Feb 22 13:54:17 2024 daemon.info dnsmasq[1]: read /tmp/hosts/dhcp.cfg01411c - 2 names
Thu Feb 22 13:54:17 2024 daemon.info dnsmasq-dhcp[1]: read /etc/ethers - 0 addresses`

**Comment by mirobiala** [comment]
Hi [pyra92](https://github.com/pyra92), you don't need to change anything. The snapshot build was working when I was testing the last changes of the driver (two weeks ago). Now it isn't. I think this is related to the recent shapshot updates from OpenWRT. I'll try to find solution but meanwhile you can try using older snapshot of the OpenWRT source which works for you. 

Regards!

**Comment by pyra92** [comment]
Figuring out how to build from source on older snapshot now thanks for the tip, will comment if I get it working!

Thanks again!

**Comment by mirobiala** [comment]
```
git checkout c6ed34940d6231a7cfadaea5f1f3ee746d78e41a
```
... in the OpenWRT master branch.

I used this revision for testing the latest  snapshot driver updates.

Regards!

**Comment by pyra92** [comment]
Awesome, I can run that for now, thanks again!

**Comment by mirobiala** [comment]
Hi [pyra92](https://github.com/pyra92), you can use the latest snapshot branch for your build. The issue is fixed, also the devices.txt file is patched automatically on build process.
