### ISSUE TITLE
devices.txt location

### ISSUE THREAD

**Issue by MachineGalaxy** [mirobiala/rtl88x2bu-cl#5]
I'm trying to compile OpenWRT with come custom drivers. 
So far, I've managed to compile it with both drivers successfully, and both my WiFI adapters are showing up. However, they are showing up as Generic MAC80211 802.11nac. I know I need to add the IDs into the devices.txt. However, I can't find the location. When I search in the staging_dir and build_dir, I can see them, but I can't find them before I run the make command.
Where would the devices.txt location be before I run the make command, or do I need to do it after and re-run make?

Thanks for the help.

**Comment by mirobiala** [comment]
Hi [MachineGalaxy](https://github.com/MachineGalaxy), the **_devices.txt_** file is located into the target rootfs : **_/usr/share/libiwinfo/devices.txt_** . You can get it from your previous build or from the OpenWRT source : **_build_dir_**. After adding devices description as mentioned in **_README_**, you can add the modified  **_devices.txt_** to **_files_** folder into the OpenWRT source to be added in the produced **_img_** files.

Btw, I will try to patch devices.txt file automatically in next release.

Regards!

**Comment by mirobiala** [comment]
Hi [MachineGalaxy](https://github.com/MachineGalaxy), you can use the latest release 1.0.2. The devices.txt file is patched automatically on build process.

Regards!
