### ISSUE TITLE
23.05.3 Issue

### ISSUE THREAD

**Issue by pmwfrd** [mirobiala/rtl88x2bu-cl#6]
This was a life saver - but since 23.05.3 has came out I can't install many plugins in LuCI (kernel error)

And I can't seem to compile this for 23.05.3 (make error) meaning I'm stuck unable to install packages in order to use this adapter

Don't suppose you know of any way to install it on the latest stable? 

Thanks again for the great work on this!

**Comment by mirobiala** [comment]
Hi @pmwfrd, 23.05.3 version actually compiles, but the driver is not working for some reason. I'll take a look, but meanwhile you can use 23.05.2 version and compile what plugins you want from the source. Include them into the build, or compile them as modules. 

Regards!

**Comment by pmwfrd** [comment]
Awesome - what's interesting is when I install 23.05.2 via Openwrt or even image builder it works great for installing packages (but obviously can't have this package)

But when I build from source (git checkout v23.05.2 / ./scripts/feeds update -a /  ./scripts/feeds install -a / etc) it acts like a snapshot with kernel errors when the stable build doesn't do this

Not sure if I'm building it wrong, as I'd expect that on snapshot but not a stable build like this (23.05.2) - I'll post on Openwrt to see if I'm building from source wrong in some way 

Eagerly await an update if it's possible, thanks again so much for your work on this, it's genuinely awesome!

**Comment by mirobiala** [comment]
Fixed in latest release v1.1.0

**Comment by pmwfrd** [comment]
Awesome, again thank you so much for your efforts!
