### ISSUE TITLE
Client/Station mode

### ISSUE THREAD

**Issue by alex3d** [mirobiala/rtl88x2bu-cl#8]
Hi @mirobiala. Thanks for this package.

I'm trying to setup AP+STA mode but it is failing for STA (even for single STA mode without combination with AP).
Do you use STA mode in your setup? (my setup is somewhat unusual - Armbian base image with linux 6.6 kernel and OpenWrt in container).

It seems that the problem with one of features you have enabled (when I comment this new block of code, then STA mode becomes functional):
https://github.com/mirobiala/rtl88x2bu-cl/blob/baa6c2334534754b2811a3f5217d76c38d9733d4/patches/0003-custom-configuration.patch#L237-L246
Are you sure all these features are actually implemented in realtek driver?

---

Also I have one small question regarding base driver sources: do you know what is the difference between RinCat's driver and [morrownr/88x2bu-20210702](https://github.com/morrownr/88x2bu-20210702)?

**Comment by mirobiala** [comment]
Hi @alex3d, you were right! The incorrect option is **_NL80211_EXT_FEATURE_CONTROL_PORT_OVER_NL80211_**. I will remove it from the patch and update the latest.

About 2nd question, when I was trying to compile OpenWRT driver for rtl88x2bu, I tried also [@morrownr](https://github.com/morrownr) and [@cilynx](https://github.com/cilynx) drivers. But only with the [@RinCat](https://github.com/RinCat)'s driver I was able to make OpenWRT to run wifi properly, so I chose that one. I compared those 3 drivers before, but can't remember what are the differences. 

Regards!

**Comment by alex3d** [comment]
Thanks.
Yet, it seems (at least) some of remaining features are not implemented in realtek driver and probably should not be advertised.
```
@NL80211_EXT_FEATURE_SCAN_FREQ_KHZ: This driver supports receiving and 
 reporting scan request with %NL80211_ATTR_SCAN_FREQ_KHZ. In order to 
report %NL80211_ATTR_SCAN_FREQ_KHZ, %NL80211_SCAN_FLAG_FREQ_KHZ must be 
included in the scan request. 
```
But there is no NL80211_SCAN_FLAG_FREQ_KHZ or NL80211_ATTR_SCAN_FREQ_KHZ in driver sources.
```
@NL80211_EXT_FEATURE_SCAN_RANDOM_SN: Driver/device supports randomizing the
SN in probe request frames if requested by %NL80211_SCAN_FLAG_RANDOM_SN.
```
But there is no NL80211_SCAN_FLAG_RANDOM_SN in driver sources.
```
@NL80211_EXT_FEATURE_SCAN_MIN_PREQ_CONTENT: Driver/device can omit all data
except for supported rates from the probe request content if requested
by the %NL80211_SCAN_FLAG_MIN_PREQ_CONTENT flag.
```
But there is no NL80211_SCAN_FLAG_MIN_PREQ_CONTENT in driver sources.

**Comment by mirobiala** [comment]
Thank you @alex3d, I will remove the unnecessary feature advertisements in next commit!
